package com.megapelis.server.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.megapelis.server.util.ServerConstant;
import lombok.*;

import java.util.Date;

/**
 * @author yadir.garcia.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = ServerConstant.TABLA_NAME_SERVER)
public class Server {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String imageBase64;

    @DynamoDBAttribute
    private String createdDate;

    @DynamoDBAttribute
    private String lastModifiedDate;

    @DynamoDBAttribute
    private String status;
}
